# @package _global_
model:
  hidden_dim: 64
  n_heads: 1
  feature_extractor_2d:
    pass_features: both
    use: true
    res_blocks: 2
    
  input_dim: 3
  volume_size: 16
  explicit_volume: true
  explicit_rendering: true
  unet:
    volume_repr: det_votri
    input_dim: 256
    model_channels: 64
    attention_aggregation: true
    blocks_per_res: 2
    channel_mult:
    - 1
    - 2
    - 4
    - 8
    attn_resolutions:
    - 8
    - 4
    - 2
    volume_out_channels: 16
    plane_channels: 16
    plane_hidden_channels: 8
    votri_channel_mult:
    - 1
    - 2
    - 4
    - 8
    - 16

data:
  novel_view_weight: 0.2

optimization:
  use_resnet: true
  lpips_weight: 0.2
  rendered_weight: 1.0
  diffusion_cfg: "zero123_configs/votri_lite.yaml"